# This is a CI workflow for the NCEPLIBS-w3emc project.
#
# This workflow builds for the Intel compiler.
#
# Ed Hartnett, 1/8/23
name: Intel
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Intel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compilers: ["CC=icc FC=ifort","CC=icx FC=ifx"]

    steps:

    - name: "Install Intel"
      uses: NOAA-EMC/ci-install-intel-toolkit@develop

    - name: "Build dependencies"
      uses: NOAA-EMC/ci-build-nceplibs@develop
      with:
        bacio-version: v2.6.0
        bufr-version: bufr_v12.0.0

    - name: "Checkout modified code"
      uses: actions/checkout@v3
      with: 
        path: w3emc

    - name: "Build w3emc"
      run: |
        ${{ matrix.compilers }} cmake -DCMAKE_PREFIX_PATH="~/bacio;~/bufr" -B w3emc/build -S w3emc
        cmake --parallel 2 --build w3emc/build

    - name: "Test w3emc"
      run: |
        ctest --test-dir w3emc/build --output-on-failure --rerun-failed --verbose
