# This is a CI workflow for the NCEPLIBS-w3emc project.
#
# This workflow builds on Linux with different CMake build options.
#
# Ed Hartnett, 1/8/23
name: Linux_options
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Linux_options:
    runs-on: ubuntu-latest
    env:
      FC: gfortran-11
      CC: gcc-11
    strategy:
      matrix:
        options: ['-DBUILD_D=OFF -DBUILD_WITH_BUFR=ON -DBUILD_WITH_EXTRA_DEPS=ON', '-DBUILD_4=OFF -DBUILD_WITH_BUFR=ON -DBUILD_WITH_EXTRA_DEPS=ON', '-DBUILD_SHARED_LIBS=ON']

    steps:
    
    - name: "Build dependencies"
      uses: NOAA-EMC/ci-build-nceplibs@develop
      with:
        bacio-version: v2.6.0
        bacio-cmake-args: -DBUILD_TESTING=OFF ${{ matrix.options == '-DBUILD_SHARED_LIBS=ON' && matrix.options || '' }}
        bufr-version: bufr_v12.0.0
        bufr-cmake-args: -DBUILD_TESTING=OFF ${{ matrix.options == '-DBUILD_SHARED_LIBS=ON' && matrix.options || '' }}

    - name: checkout-w3emc
      uses: actions/checkout@v4
      with: 
        path: w3emc

    - name: build-w3emc
      run: |
        set -x
        cmake -S w3emc -B w3emc/build -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-bacio;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-bufr" -DCMAKE_INSTALL_PREFIX="~/w3emc/install" ${{ matrix.options }}
        cmake --build w3emc/build --parallel 2 --verbose

    - name: test-w3emc
      run: |
        ctest --test-dir w3emc/build --output-on-failure --rerun-failed --verbose
        cmake --install w3emc/build
