# This is a CI workflow for the NCEPLIBS-w3emc project.
#
# This workflow builds on Linux with different versions of the
# dependent packages.
#
# Ed Hartnett, 1/8/23
name: Linux_versions
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Linux_versions:
    runs-on: ubuntu-latest
    env:
      FC: gfortran-11
      CC: gcc-11
    strategy:
      matrix:
        bacio-version: [2.4.1, 2.5.0]

    steps:
    
    - name: checkout-bacio
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-bacio
        path: bacio
        ref: v${{ matrix.bacio-version }}
    
    - name: cache-bacio
      id: cache-bacio
      uses: actions/cache@v2
      with:
        path: ~/bacio
        key: bacio-${{ runner.os }}-v${{ matrix.bacio-version }}

    - name: build-bacio
      if: steps.cache-bacio.outputs.cache-hit != 'true'
      run: |
        cd bacio
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/bacio
        make -j2
        make install

    - name: checkout-w3emc
      uses: actions/checkout@v2
      with: 
        path: w3emc

    - name: build-w3emc
      run: |
        cd w3emc
        mkdir build 
        cd build
        cmake .. -DCMAKE_PREFIX_PATH=~/bacio
        make -j2

    - name: test-w3emc
      run: |
        cd w3emc/build
        ctest --output-on-failure --rerun-failed --verbose
