# This is a CI workflow for the NCEPLIBS-w3emc project.
#
# This workflow builds for the MacOS system.
#
# Ed Hartnett, 1/8/23
name: MacOS
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  MacOS:
    runs-on: macos-latest
    env:
      FC: ${{ matrix.compiler }}
    strategy:
      matrix:
        compiler: [gfortran-11, gfortran-12]
        bacio-version: [2.4.1, 2.5.0, 2.6.0]

    steps:
    
    - name: "Build dependencies"
      uses: NOAA-EMC/ci-build-nceplibs@develop
      with:
        bacio-version: ${{ matrix.bacio-version }}
        bufr-version: bufr_v11.7.1

    - name: checkout-w3emc
      uses: actions/checkout@v4
      with: 
        path: w3emc

    - name: build-w3emc
      run: |
        cmake -S w3emc -B w3emc/build -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-bacio;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-bufr"
        cmake --build w3emc/build --parallel 2 --verbose

    - name: test-w3emc
      run: ctest --test-dir w3emc/build --output-on-failure --rerun-failed --verbose

